service_name: "frontendproxy"
image_name: "ghcr.io/open-telemetry/demo:1.10.0-frontendproxy"
ports:
  - "10000:10000"
  - "8080:8080"
memory_limit: "50M"
locust_web_host: "loadgenerator"
locust_web_port: "8089"
jaeger_host: "jaeger"
jaeger_port: "16686"
imageprovider_host: "imageprovider"
imageprovider_port: "8081"
grafana_host: "grafana"
grafana_port: "3000"
frontend_host: "frontend"
frontend_port: "8080"