apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: app-config
spec:
  metrics:
    enabled: true
    recordErrorCodes: true
  logging:
    apiLogging:
      enabled: true
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "otel-gateway-collector:4317:4317"
      isSecure: true
      protocol: grpc