apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-traces
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse
      username: default
      tlsSkipVerify: false
    secureJsonData:
      password: