# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Elasticsearch
    uid: webstore-logs
    type: elasticsearch
    url: http://elasticsearch:9200/
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      database: otel-logs-*
      index: otel-logs-*
      logLevelField: severity.text.keyword
      logMessageField: body
      timeField: observedTimestamp
      esVersion: "9.2.0"
