# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: OpenSearch
    uid: webstore-logs
    type: grafana-opensearch-datasource
    url: http://opensearch:9200/
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      database: otel-logs-*
      flavor: opensearch
      logLevelField: severity.text.keyword
      logMessageField: body
      pplEnabled: true
      timeField: observedTimestamp
      version: 3.4.0
