
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-demo
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/part-of: opentelemetry-demo

