# Source: opentelemetry-demo/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/version: "12.1.1"
data:
  
  plugins: {{ .Values.grafana.plugins }}
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = true
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Admin
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    serve_from_sub_path = true
    {{- if and .Values.azure .Values.azure.workloadIdentity .Values.azure.workloadIdentity.enabled }}
    [azure]
    # Workload Identity authentication - uses AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_FEDERATED_TOKEN_FILE env vars
    workload_identity_enabled = true
    workload_identity_tenant_id = {{ .Values.azure.tenantId }}
    workload_identity_client_id = {{ .Values.azure.workloadIdentity.clientId }}
    {{- end }}
    {{- if and .Values.grafana.alerting .Values.grafana.alerting.smtp }}
    [smtp]
    enabled = {{ .Values.grafana.alerting.smtp.enabled | default false }}
    host = {{ .Values.grafana.alerting.smtp.host | default "smtp.azurecomm.net" }}:{{ .Values.grafana.alerting.smtp.port | default 587 }}
    user = {{ .Values.grafana.alerting.smtp.user | default "" }}
    password = {{ .Values.grafana.alerting.smtp.password | default "" }}
    from_address = {{ .Values.grafana.alerting.smtp.fromAddress | default "" }}
    from_name = {{ .Values.grafana.alerting.smtp.fromName | default "Grafana Alerts" }}
    skip_verify = {{ .Values.grafana.alerting.smtp.skipVerify | default false }}
    {{- end }}
    [unified_alerting]
    enabled = true
    [alerting]
    enabled = false
