apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if and .Values.azure .Values.azure.workloadIdentity .Values.azure.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.azure.workloadIdentity.clientId }}"
  {{- end }}
  name: grafana-sa
  namespace: {{ .Values.namespace }}