apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "{{ .Values.grafana.clientid }}"
    azure.workload.identity/tenant-id: "{{ .Values.azure_tenant_id }}"

  name: grafana-sa
  namespace: {{ .Values.namespace }}