apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo
  namespace: argocd
  # TODO: Enable image updater
  annotations:
    argocd-image-updater.argoproj.io/image-list: checkout=sherlocksai/otel-demo-checkout:latest,product-catalog=sherlocksai/otel-demo-product-catalog:latest
    argocd-image-updater.argoproj.io/checkout.update-strategy: digest
    argocd-image-updater.argoproj.io/checkout.force-update: "true"
    argocd-image-updater.argoproj.io/checkout.pull-secret: pullsecret:argocd/argocd-image-updater-secret
    argocd-image-updater.argoproj.io/checkout.helm.image-name: components.checkout.imageOverride.repository
    argocd-image-updater.argoproj.io/checkout.helm.image-tag: components.checkout.imageOverride.tag
    argocd-image-updater.argoproj.io/product-catalog.update-strategy: digest
    argocd-image-updater.argoproj.io/product-catalog.force-update: "true"
    argocd-image-updater.argoproj.io/product-catalog.pull-secret: pullsecret:argocd/argocd-image-updater-secret
    argocd-image-updater.argoproj.io/product-catalog.helm.image-name: components.product-catalog.imageOverride.repository
    argocd-image-updater.argoproj.io/product-catalog.helm.image-tag: components.product-catalog.imageOverride.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    chart: opentelemetry-demo
    repoURL: https://migrateai.github.io/opentelemetry-helm-charts
    targetRevision: 0.37.6
    helm:
      releaseName: my-otel-demo
      parameters:
        - forceString: true
          name: components.checkout.imageOverride.repository
          value: sherlocksai/otel-demo-checkout
        - forceString: true
          name: components.checkout.imageOverride.tag
          value: latest@sha256:595a82b78308c9e679405d5761c43e061e0df72975c91cfac047240e303a3604
        - forceString: true
          name: components.product-catalog.imageOverride.repository
          value: sherlocksai/otel-demo-product-catalog
        - forceString: true
          name: components.product-catalog.imageOverride.tag
          value: latest@sha256:034493521afd4372316cae192a2d82bcf04f6d68d545d180010dd6b741a88e04
        - forceString: true
          name: components.recommendation.imageOverride.repository
          value: sherlocksai/otel-demo-recommendation
        - forceString: true
          name: components.recommendation.imageOverride.tag
          value: latest@sha256:17296398f48cee5ef6be104cac41dc5601e756a4e53dd03e426914eabe1cb86c
        - forceString: true
          name: components.cart.imageOverride.repository
          value: sherlocksai/otel-demo-cart
        - forceString: true
          name: components.cart.imageOverride.tag
          value: latest
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: lyrid-016d2205-3e0f-4ef0-aa64-d7debe01f0b1
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: jaeger
      namespace: lyrid-016d2205-3e0f-4ef0-aa64-d7debe01f0b1
      jsonPointers:
        - /spec/selector
    - group: apps
      kind: StatefulSet
      name: opensearch
      namespace: lyrid-016d2205-3e0f-4ef0-aa64-d7debe01f0b1
      jsonPointers:
        - /spec
    - kind: ConfigMap
      name: grafana-dashboards
      namespace: lyrid-016d2205-3e0f-4ef0-aa64-d7debe01f0b1
      jsonPointers:
        - /metadata/annotations
    - group: apps
      kind: Deployment
      name: grafana
      namespace: lyrid-016d2205-3e0f-4ef0-aa64-d7debe01f0b1
      jsonPointers:
        - /spec
