apiVersion: v1
kind: Secret
metadata:
  name: workshop-secret
  namespace: default
type: Opaque
stringData:
  instance: [instance-name]-shop-demo
  app: [instance-name]-store
  env: [instance-name]-shop-demo
  deployment: "deployment.environment=[instance-name]-shop-demo"
  realm: [realm]
  access_token: [ingest-token]
  api_token: [api-token]
  rum_token: [rum-token]
  hec_token: [hec-token]
  hec_url: [hec-url]
  url: [full url]
  appd_token: ["appd-token"]
  flagd_auth: "true/false"
  flagd_user: "user"
  flagd_pw: "pw"
data:
  TEAGENT_ACCOUNT_TOKEN:[TEAGent-Token]