---
- name: Pull the latest Docker image
  docker_image:
    name: "{{ image_name }}"
    source: pull

- name: Deploy Service
  become: true
  docker_container:
    name: "{{ service_name }}"
    image: "{{ image_name }}"
    env:
      METRICS_STORAGE_TYPE: "{{ metrics_storage_type }}"
    restart_policy: "{{ restart_policy }}"
    command: "{{ command }}"
    memory: "{{ memory_limit }}"
    state: "{{ state }}"
    ports: "{{ ports }}"
    network_mode: "{{ network_name }}"
    networks:
      - name: "{{ network_name }}"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_options_max_size }}"
      max-file: "{{ log_options_max_file }}"
      tag: "{{ service_name }}"