apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/version: v2.55.1
    app.kubernetes.io/part-of: prometheus
  name: opentelemetry-demo-prometheus-server
  namespace: otel-demo
  annotations:
    {}