service_name: "loadgenerator"
image_name: "ghcr.io/open-telemetry/demo:1.10.0-loadgenerator"
ports: "8089"
otlp_metrics_temporality_preference : "cumulative"
memory_limit: "1G"
otlp_exporter_traces_endpoint: "http://otelcol:8080/otlp-http/v1/traces"
frontendproxy_port: "8080"
frontendproxy_addr: "http://frontendproxy:8080"
locust_users: "10"
kafkaservice_addr: "kafka:9092"
protobuf_python: "python"
locust_web_host: "0.0.0.0"
locust_headless: "false"
locust_autostart: "true"
locust_browser_traffic_enabled: "true"