name: "Build Docker Images"

on:
  release:
    types: [published]

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    name: "Build and push images"
    env:
      RELEASE_NAME: "${{ github.release.tag_name }}"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build docker image
        run: make build-docker-images
      - name: push docker image
        run: make push-docker-images
