# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build_images:
    uses: ./.github/workflows/build-images.yml

  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: install dependencies
      run: npm install

    - name: run markdownlint
      run: make markdownlint

  yamllint:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install yamllint
      run: make install-yamllint

    - name: run yamllint
      run: yamllint . -f github

  misspell:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: run misspell
      run: make misspell

  markdownlinkcheck:
    name: markdownlinkcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run link check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.github/.mlc_config.json'

  sanity:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: run sanitycheck.py
      run: python3 ./internal/tools/sanitycheck.py

  checklicense:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3
    - name: install tools
      run: make install-tools
    - name: run checklicense
      run: make checklicense
