# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_images:
<<<<<<< HEAD
    permissions: # required by the reusable workflow
      contents: read
      packages: write
    uses: ./.github/workflows/component-build-images.yml
=======
    uses: ./.github/workflows/build-and-push-images.yaml
>>>>>>> dynatrace
    with:
      push: false
      version: "dev"

  markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - name: check out code
        uses: actions/checkout@v5
      - name: install dependencies
        run: npm install
      - name: run markdownlint
        run: make markdownlint

  yamllint:
    runs-on: ubuntu-24.04
    steps:
      - name: check out code
        uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: install yamllint
        run: make install-yamllint
      - name: run yamllint
        run: yamllint . -f github

  misspell:
    runs-on: ubuntu-24.04
    steps:
      - name: check out code
        uses: actions/checkout@v5
      - name: run misspell
        run: make misspell

  checklinks:
    name: linkspector
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          level: info
          fail_level: any
          config_file: ".linkspector.yml"

  sanity:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: run sanitycheck.py
        run: python3 ./internal/tools/sanitycheck.py
<<<<<<< HEAD

  checklicense:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v5
      - name: install tools
        run: make install-tools
      - name: run checklicense
        run: make checklicense
=======
>>>>>>> dynatrace
