# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

on:
  pull_request_target:
    branches: [ main ]

permissions:
  contents: read

jobs:
  dependabot-auto-update-protobuf-diff:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    # Only run this job if the PR is opened by dependabot and the last commit is from dependabot
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.DEPENDABOT_TOKEN }}
      - name: Generate
        run: make clean docker-generate-protobuf
      - name: Commit only if there are changes
        run: |
          if ! git diff --quiet; then
            git config user.name "dependabot[bot]"
            git config user.email "49699333+dependabot[bot]@users.noreply.github.com"
            git add .
            git commit -s -m "chore: update protobuf"
            git push
          fi
