# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Gradle wrapper validation
on:
  pull_request:
    paths:
      - '**/gradle/wrapper/**'
  push:
    paths:
      - '**/gradle/wrapper/**'

permissions:
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v4.4.2
