name: CI/CD Pipeline by Fortress Technologies Inc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push accountingservice
        working-directory: src/accountingservice
        run: |
          docker build -t iscanprint/accountingservice:3.0 .
          docker push iscanprint/accountingservice:3.0

      - name: Build and push adservice
        working-directory: src/adservice
        run: |
          docker build -t iscanprint/adservice:3.0 .
          docker push iscanprint/adservice:3.0

      - name: Build and push cartservice
        working-directory: src/cartservice/src
        run: |
          docker build -t iscanprint/cartservice:3.0 .
          docker push iscanprint/cartservice:3.0

      - name: Build and push checkoutservice
        working-directory: src/checkoutservice
        run: |
          docker build -t iscanprint/checkoutservice:3.0 .
          docker push iscanprint/checkoutservice:3.0

      - name: Build and push currencyservice
        working-directory: src/currencyservice
        run: |
          docker build -t iscanprint/currencyservice:3.0 .
          docker push iscanprint/currencyservice:3.0

      - name: Build and push emailservice
        working-directory: src/emailservice
        run: |
          docker build -t iscanprint/emailservice:3.0 .
          docker push iscanprint/emailservice:3.0

      - name: Build and push frauddetectionservice
        working-directory: src/frauddetectionservice
        run: |
          docker build -t iscanprint/frauddetectionservice:3.0 .
          docker push iscanprint/frauddetectionservice:3.0

      - name: Build and push frontend
        working-directory: src/frontend
        run: |
          docker build -t iscanprint/frontend:3.0 .
          docker push iscanprint/frontend:3.0

      - name: Build and push frontendproxy
        working-directory: src/frontendproxy
        run: |
          docker build -t iscanprint/frontendproxy:3.0 .
          docker push iscanprint/frontendproxy:3.0

      - name: Build and push imageprovider
        working-directory: src/imageprovider
        run: |
          docker build -t iscanprint/imageprovider:3.0 .
          docker push iscanprint/imageprovider:3.0

      - name: Build and push kafka
        working-directory: src/kafka
        run: |
          docker build -t iscanprint/kafka:3.0 .
          docker push iscanprint/kafka:3.0

      - name: Build and push loadgenerator
        working-directory: src/loadgenerator
        run: |
          docker build -t iscanprint/loadgenerator:3.0 .
          docker push iscanprint/loadgenerator:3.0

      - name: Build and push paymentservice
        working-directory: src/paymentservice
        run: |
          docker build -t iscanprint/paymentservice:3.0 .
          docker push iscanprint/paymentservice:3.0

      - name: Build and push productcatalogservice
        working-directory: src/productcatalogservice
        run: |
          docker build -t iscanprint/productcatalogservice:3.0 .
          docker push iscanprint/productcatalogservice:3.0

      - name: Build and push quoteservice
        working-directory: src/quoteservice
        run: |
          docker build -t iscanprint/quoteservice:3.0 .
          docker push iscanprint/quoteservice:3.0

      - name: Build and push recommendationservice
        working-directory: src/recommendationservice
        run: |
          docker build -t iscanprint/recommendationservice:3.0 .
          docker push iscanprint/recommendationservice:3.0

      - name: Build and push shippingservice
        working-directory: src/shippingservice
        run: |
          docker build -t iscanprint/shippingservice:3.0 .
          docker push iscanprint/shippingservice:3.0
