name: Merge Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge:
    permissions:
      # These are defensively set to read to ensure that no repository or
      # organization level permissions can override. The required permissions
      # are actually granted via the required PAT used with this workflow.
      contents: read
      pull-requests: read
      issues: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.MERGE_UPSTREAM_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream main branch
        id: merge-upstream
        run: |
          TS=$(date +"%Y%m%d_%H%M%S")
          TS_FULL=$(date +"%Y-%m-%d %H:%M:%S")

          git remote add upstream $UPSTREAM_REPO_URL
          git fetch upstream
          git checkout main

          AHEAD=$(git rev-list upstream/main..main --count)
          BEHIND=$(git rev-list main..upstream/main --count)

          if [ $BEHIND -eq 0 ]; then
            echo "::notice:: main already up-to-date with upstream/main, no merge needed"
            exit 0
          fi

          echo "::notice:: main is behind upstream/main by $BEHIND commits and ahead by $AHEAD commits"

          git checkout -b chore/sync-upstream_$TS

          git merge upstream/main -m "chore: sync with upstream main branch - $TS_FULL"

          if [ $? -ne 0 ]; then
            echo "::error:: Merge failed; possibly due to merge conflicts"
            echo "SUCCESS=2" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "::notice:: Merge successful"
          echo "SUCCESS=1" >> $GITHUB_OUTPUT
        env:
          UPSTREAM_REPO_URL: ${{ vars.UPSTREAM_REPO_URL }}

      - name: Push changes and create pull request
        if: steps.merge-upstream.outputs.SUCCESS == '1'
        run: |
          TS=$(date +"%Y%m%d_%H%M%S")
          TS_FULL=$(date +"%Y-%m-%d %H:%M:%S")

          git push origin HEAD:chore/sync-upstream_$TS

          gh pr create --title "chore: sync with upstream main branch - $TS_FULL" \
            --fill-verbose \
            --base main

          echo "::notice:: Pull request created for merged changes"
        env:
          GH_TOKEN: ${{ secrets.MERGE_UPSTREAM_TOKEN }}

      - name: Create issue if merge failed
        if: steps.merge-upstream.outputs.SUCCESS == '2'
        run: |
          TS_FULL=$(date +"%Y-%m-%d %H:%M:%S")

          gh issue create --title='Failed to merge upstream main branch - $TS_FULL' \
            --body='Merge conflict or other issue occurred during upstream merge. Please resolve manually.'

          echo "::notice:: Issue created for merge failure"
        env:
          GH_TOKEN: ${{ secrets.MERGE_UPSTREAM_TOKEN }}
