name: Merge Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream main branch and create pull request
        id: merge-upstream
        run: |
          git remote add $UPSTREAM_REMOTE $UPSTREAM_REPO_URL

          ./merge-upstream.sh
        working-directory: ./newrelic/scripts
        env:
          UPSTREAM_REPO_URL: ${{ vars.MERGE_UPSTREAM_REPO_URL }}
          UPSTREAM_REMOTE: upstream
          TARGET_REPO: ${{ vars.MERGE_UPSTREAM_TARGET_REPO }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue if merge failed
        if: ${{ failure() }}
        run: |
          echo "::error:: Merge failed; possibly due to merge conflicts"

          TS_FULL=$(date +"%Y-%m-%d %H:%M:%S")

          gh issue create --title "Failed to merge upstream main branch on $TS_FULL" \
            --body "This issue was generated on $TS_FULL by the Merge Upstream action due to a merge conflict or other issue during the upstream merge. Please resolve manually." \
            --label 'merge-failure' \
            --repo $TARGET_REPO

          echo "::notice:: Issue created for merge failure"
        env:
          TARGET_REPO: ${{ vars.MERGE_UPSTREAM_TARGET_REPO }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
