name: merge-upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream main branch
        run: |
          TS=$(date +"%Y%m%d_%H%M%S")
          TS_FULL=$(date +"%Y-%m-%d %H:%M:%S")

          git remote add upstream $UPSTREAM_REPO_URL
          git fetch upstream
          git checkout main

          git remote -v

          AHEAD=$(git rev-list upstream/main..main --count)
          BEHIND=$(git rev-list main..upstream/main --count)

          if [ $BEHIND -eq 0 ]; then
            echo "::notice:: main already up-to-date with upstream/main, no merge needed"
            exit 0
          fi

          echo "::notice:: main is behind upstream/main by $BEHIND commits and ahead by $AHEAD commits"

          git checkout -b chore/sync-upstream_$TS

          git merge upstream/main -m "chore: sync with upstream main branch - $TS_FULL"

          if [ $? -ne 0 ]; then
            echo "::error:: Merge failed; possibly due to merge conflicts"
            # fail the action
            exit 1
          fi

          echo "::notice:: Merge successful"
        env:
          UPSTREAM_REPO_URL: ${{ vars.UPSTREAM_REPO_URL }}

      - name: Push changes and create pull request
        run: |
          TS_FULL=$(date +"%Y-%m-%d %H:%M:%S")

          git push origin head
          gh pr create --title "chore: sync with upstream main branch - $TS_FULL" \
            --fill-verbose \
            --base main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
