name: Merge Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.0
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge upstream main branch and create pull request
        id: merge-upstream
        run: |
          git remote add $UPSTREAM_REMOTE $UPSTREAM_REPO_URL

          ./merge-upstream.sh

          if [ $? -ne 0 ]; then
            echo "::error:: Merge failed; possibly due to merge conflicts"
            echo "SUCCESS=1" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "::notice:: Merge successful"
          echo "SUCCESS=1" >> $GITHUB_OUTPUT
        working-directory: ./newrelic/scripts
        env:
          UPSTREAM_REPO_URL: ${{ vars.UPSTREAM_REPO_URL }}
          UPSTREAM_REMOTE: upstream
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue if merge failed
        if: steps.merge-upstream.outputs.SUCCESS == '1'
        run: |
          TS_FULL=$(date +"%Y-%m-%d %H:%M:%S")

          gh issue create --title='Failed to merge upstream main branch - $TS_FULL' \
            --body='Merge conflict or other issue occurred during upstream merge. Please resolve manually.'

          echo "::notice:: Issue created for merge failure"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue if pull request creation failed
        if: steps.merge-upstream.outputs.SUCCESS == '2'
        run: |
          TS_FULL=$(date +"%Y-%m-%d %H:%M:%S")

          gh issue create --title='Failed to merge upstream main branch - $TS_FULL' \
            --body='Creation of pull request failed. Please resolve manually.'

          echo "::notice:: Issue created for pull request creation failure"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
