name: test-build

on:
  push:
    paths:
      - 'src/**'
      - '!src/**.md'
      - 'test/**'
      - 'dynatrace/**'
      - 'docker-compose.yml'
      - '.env.override'

jobs:
  build:
    uses: ./.github/workflows/build-and-push-images.yaml
    with:
      push: false
    secrets: inherit
